// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTemplate.Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(IspitContext))]
    [Migration("20260210123619_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTemplate.Models.Automobil", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<long>("CenaPoDanu")
                        .HasColumnType("bigint");

                    b.Property<long>("Godiste")
                        .HasColumnType("bigint");

                    b.Property<long>("Kilometraza")
                        .HasColumnType("bigint");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Sedista")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("automobili");
                });

            modelBuilder.Entity("WebTemplate.Models.Iznajmljen", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<long?>("DanIznajmljen")
                        .HasColumnType("bigint");

                    b.Property<int?>("IznajmljenAutomobilFK")
                        .HasColumnType("int");

                    b.Property<int?>("KorisnikIznajmljujeFK")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IznajmljenAutomobilFK")
                        .IsUnique()
                        .HasFilter("[IznajmljenAutomobilFK] IS NOT NULL");

                    b.HasIndex("KorisnikIznajmljujeFK");

                    b.ToTable("iznajmljeni");
                });

            modelBuilder.Entity("WebTemplate.Models.Korisnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BrojVozacke")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("korisnici");
                });

            modelBuilder.Entity("WebTemplate.Models.Iznajmljen", b =>
                {
                    b.HasOne("WebTemplate.Models.Automobil", "IznajmljenAutomobil")
                        .WithOne("IznajmljitiKorisniku")
                        .HasForeignKey("WebTemplate.Models.Iznajmljen", "IznajmljenAutomobilFK");

                    b.HasOne("WebTemplate.Models.Korisnik", "KorisnikIznajmljuje")
                        .WithMany("IznajmljeniAuto")
                        .HasForeignKey("KorisnikIznajmljujeFK");

                    b.Navigation("IznajmljenAutomobil");

                    b.Navigation("KorisnikIznajmljuje");
                });

            modelBuilder.Entity("WebTemplate.Models.Automobil", b =>
                {
                    b.Navigation("IznajmljitiKorisniku");
                });

            modelBuilder.Entity("WebTemplate.Models.Korisnik", b =>
                {
                    b.Navigation("IznajmljeniAuto");
                });
#pragma warning restore 612, 618
        }
    }
}
